apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kustomize-patcher-role
rules:
  - apiGroups: ["themesama.com"]
    resources: ["patchdeployments"]
    verbs: ["get", "list", "watch", "update", "patch"]
