apiVersion: v1
kind: Service
metadata:
  name: kustomize-patcher-svc
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8443
  selector:
    app: kustomize-patcher
